# -*- coding: utf-8 -*-
"""TF1 Agente Gastronomico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8oJM1PHnW3yklNpOjnI1o1jmccMki6c

# Asistente Gastronómico con LangChain
Proyecto Final - Agente Inteligente para Emprendedores Gastronómicos
"""

!pip install -qU langchain langchain_openai langchain-core langchain-community langgraph langchain-tavily

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade --quiet  langchain-community

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade --quiet  youtube_search

import os
os.environ['OPENAI_API_KEY'] = "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"
os.environ["TAVILY_API_KEY"] = "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"

from langchain.agents import create_react_agent, AgentExecutor
from langchain import hub
from langchain.tools import Tool
from langchain.memory import ConversationBufferMemory
from langchain_openai import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain_community.tools.tavily_search import TavilySearchResults

from langchain_core.runnables import RunnableBranch, RunnableLambda

with open("reglas_empleados.txt") as archivo:
    reglas = archivo.read()

import pandas as pd
from datetime import datetime, timedelta

productos_df = pd.read_csv("productos_kattys.csv")
pedidos_df = pd.read_csv("pedidos_programados.csv")
recetas_df = pd.read_csv("recetas_katty.csv")

#Creamos la memoria temporal
contexto = []

base_prompt = hub.pull("hwchase17/react")

# Crea un nuevo prompt con reglas + prompt base
prompt = PromptTemplate(
    template=reglas + "\n\n" + base_prompt.template,
    input_variables=base_prompt.input_variables
)

#youtube
from langchain_community.tools import YouTubeSearchTool
youtube = YouTubeSearchTool()

def calcular_costos(params):
    producto = params["producto"]
    ingredientes = params["ingredientes"]
    total = sum(cant * 1.0 for cant in ingredientes.values())  # Aquí asumes que cada ingrediente tiene un precio unitario, o simulas uno
    precio_sugerido = round(total * 1.5, 2)
    return f"Costo total de '{producto}': ${total:.2f}. Precio sugerido: ${precio_sugerido:.2f}."

def ver_productos_con_stock_bajo():
    bajo_stock = inventario_df[inventario_df['cantidad_actual'] < inventario_df['cantidad_minima']]
    if bajo_stock.empty:
        return "Todos los insumos están en niveles adecuados."
    return "Insumos con stock bajo:\n" + "\n".join([
        f"- {row['insumo']}: {row['cantidad_actual']} unidades (mínimo: {row['cantidad_minima']})"
        for _, row in bajo_stock.iterrows()
    ])

def generar_lista_compras(inventario, pedidos):
    faltantes = {}
    for pedido in pedidos:
        for insumo, requerido in pedido['ingredientes'].items():
            actual = inventario.get(insumo, 0)
            if actual < requerido:
                faltantes[insumo] = faltantes.get(insumo, 0) + (requerido - actual)
    return f"Insumos faltantes: {faltantes}" if faltantes else "No faltan insumos."

def consultar_productos(_input=None):
    productos = productos_df[['producto', 'tiempo_preparacion_horas', 'precio_sugerido']].to_dict(orient='records')
    return "Productos disponibles:\n" + "\n".join([
        f"- {p['producto']} (demora: {p['tiempo_preparacion_horas']}h, S/. {p['precio_sugerido']})"
        for p in productos
    ])

def ver_pedidos_programados(fecha_str=None):
    if fecha_str and isinstance(fecha_str, str):
        try:
            fecha = datetime.strptime(fecha_str, "%Y-%m-%d").date()
            filtrado = pedidos_df[pedidos_df['fecha_entrega'] == fecha_str]
        except ValueError:
            return "Fecha no válida. Usa formato AAAA-MM-DD."
    else:
        filtrado = pedidos_df

    if filtrado.empty:
        return "No hay pedidos programados para esa fecha." if fecha_str else "No hay pedidos programados."
    return "Pedidos programados:\n" + "\n".join([
        f"- {row['cliente']} - {row['producto']} ({row['fecha_entrega']}) - {row['estado']}"
        for _, row in filtrado.iterrows()
    ])

def obtener_ingredientes_csv(producto):
    ingredientes = recetas_df[recetas_df['producto'] == producto]
    if not ingredientes.empty:
        return ingredientes[['insumo', 'cantidad']].to_dict(orient='records')
    return None

def calcular_produccion_requerida(fecha_str=None):
    hoy = fecha_str or datetime.now().strftime("%Y-%m-%d")
    pedidos_hoy = pedidos_df[pedidos_df['fecha_entrega'] == hoy]
    if pedidos_hoy.empty:
        return "No hay pedidos programados para hoy."

    conteo = pedidos_hoy['producto'].value_counts()
    return "Producción requerida para hoy:\n" + "\n".join([
        f"- {producto}: {cantidad} unidades"
        for producto, cantidad in conteo.items()
    ])

# Runnables
tool_ingredientes_runnable = RunnableLambda(obtener_ingredientes_csv)

tavily = TavilySearchResults()

tool_tavily = Tool(
    name="buscar_en_la_web",
    func=tavily.run,
    description="Busca información actualizada y precisa en internet sobre productos o ingredientes."
)

# Condiciones
es_base_de_datos = lambda x: isinstance(x, dict) and x.get("producto") in recetas_df['producto'].values

selector = RunnableBranch(
    (es_base_de_datos, tool_ingredientes_runnable),
    tavily.run
)

tools = [
    Tool(name="calcular_costos", func=calcular_costos, description="Calcula el costo de un producto"),
    Tool(name="generar_lista_compras", func=generar_lista_compras, description="Genera lista de compras según pedidos"),
    Tool(name="consultar_productos", func=consultar_productos, description="Muestra productos disponibles y su tiempo de preparación"),
    Tool(name="youtube_search", func=youtube.run, description="Busca videos en YouTube relacionados con un tema"),
    Tool(name="ver_pedidos_programados", func=ver_pedidos_programados, description="Muestra los pedidos programados, se puede ingresar una fecha AAAA-MM-DD"),
    Tool(name="ingredientes_o_descripcion",func=selector.invoke,description="Busca los ingredientes del producto si está en la base. Si no, lo busca en fuentes externas como Tavily."),
    Tool(name="buscar_web", func=tool_tavily.run, description="Busca información actualizada y precisa en internet sobre recetas, productos o ingredientes."),
    Tool(name="ver_productos_con_stock_bajo",func=ver_productos_con_stock_bajo,description="Muestra los insumos con niveles de stock por debajo del mínimo recomendado."),
    Tool(name="calcular_produccion_requerida",func=calcular_produccion_requerida,description="Muestra cuántos productos debes preparar según los pedidos programados para hoy (o para una fecha específica AAAA-MM-DD).")
    ]

memory = ConversationBufferMemory(memory_key="chat_history")
llm = ChatOpenAI(model="gpt-4", temperature=0)

agent = create_react_agent(llm=llm, tools=tools, prompt=prompt)

executor = AgentExecutor(
    agent=agent,
    tools=tools,
    memory=memory,
    verbose=True,
    handle_parsing_errors=True
)

print("\n--- Asistente Gastronómico Activado ---\n")

executor.invoke({"input": "¿Qué pedidos pendientes tenemos el 2025-05-02?"})

executor.invoke({"input": "¿Cuál es el precio sugerido y el tiempo de preparación de la torta de chocolate?"})

executor.invoke({"input": "No recuerdo el proceso de decoración para el pedido de cupcakes."})

executor.invoke({"input": "¿Vendemos torta de pecanas?¿Cómo se preparan?"})

executor.invoke({"input": "¿Qué ingredientes lleva la Torta de chocolate?"})
